// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxzbdLlxs-l14izbx1HxCc3dNwlsgVFY',
    appId: '1:1020280417829:web:0f5539b52461be1fbcd9cc',
    messagingSenderId: '1020280417829',
    projectId: 'fir-fluttercodelab-6f5da',
    authDomain: 'fir-fluttercodelab-6f5da.firebaseapp.com',
    storageBucket: 'fir-fluttercodelab-6f5da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8u_H7PAUWHDo8Ih_vM_Fy5zKMUxYZvEU',
    appId: '1:1020280417829:android:6e2523df4abe83babcd9cc',
    messagingSenderId: '1020280417829',
    projectId: 'fir-fluttercodelab-6f5da',
    storageBucket: 'fir-fluttercodelab-6f5da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIdSAI-Hv_XxnVZteaXyAWWgHawP8OFf0',
    appId: '1:1020280417829:ios:539849c67b02231cbcd9cc',
    messagingSenderId: '1020280417829',
    projectId: 'fir-fluttercodelab-6f5da',
    storageBucket: 'fir-fluttercodelab-6f5da.appspot.com',
    iosClientId: '1020280417829-oi0lc26cqjifkoj1lnb8pb9oe64jnrq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIdSAI-Hv_XxnVZteaXyAWWgHawP8OFf0',
    appId: '1:1020280417829:ios:539849c67b02231cbcd9cc',
    messagingSenderId: '1020280417829',
    projectId: 'fir-fluttercodelab-6f5da',
    storageBucket: 'fir-fluttercodelab-6f5da.appspot.com',
    iosClientId: '1020280417829-oi0lc26cqjifkoj1lnb8pb9oe64jnrq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
